services:
  one-api:
    image: martialbe/one-api:v0.14.13
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    networks:
      - 1panel-network
    volumes:
      - ./data:/data
    environment:
      - TZ=${TZ}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
