services:
  one-api:
    image: thedaviddelta/lingva-translate:latest

    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    networks:
      - 1panel-network
    volumes:
      - ./data:/data
    environment:
      - site_domain=${SITE_DOMAIN}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
