services:
  kener:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    environment:
      - KENER_SECRET_KEY=${KENER_SECRET_KEY}
      - ORIGIN=http://localhost:3000
    image: xream/sub-store:http-meta
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
